/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.BuoiHopManagerFrame;

import Bean.HoKhauBean;
import controllers.BuoiHopController.DiemDanhBuoiHopController;
import controllers.BuoiHopController.ViewBuoiHopController;
import models.BuoiHop;
import services.BuoiHopService;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.List;

/**
 *
 */
public class CapNhatBuoiHop extends javax.swing.JFrame {

    /**
     * Creates new form CapNhatBuoiHop
     */
    public CapNhatBuoiHop() {
        initComponents();
    }
    private JFrame parentFrame;
    BuoiHop buoiHop;
    private ViewBuoiHopController parentController;
    private CapNhatBuoiHop controller;
    private List<BuoiHop> listBuoiHop;
    DefaultTableModel model;
    public CapNhatBuoiHop(ViewBuoiHopController parentController, JFrame parentFrame, BuoiHop bh) {
        this.parentController = parentController;
        this.parentFrame = parentFrame;
        this.buoiHop = bh;
        this.parentFrame.setEnabled(false);
        initComponents();
        setBuoiHop();

        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                if (JOptionPane.showConfirmDialog(null, "Are you sure to close??", "Warning!!", JOptionPane.YES_NO_OPTION) == 0) {
                    close();
                }
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DiaDiem = new javax.swing.JTextField();
        ChuDe = new javax.swing.JTextField();
        ThoiGian = new com.toedter.calendar.JDateChooser();
        capNhatbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        thoatbtn = new javax.swing.JButton();
        maBuoiHop = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        xoabtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DiaDiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        ChuDe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ChuDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChuDeActionPerformed(evt);
            }
        });

        ThoiGian.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        capNhatbtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        capNhatbtn.setText("Cập nhât");
        capNhatbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capNhatbtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Địa Điểm");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Thời gian");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Chủ đề");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Cập nhật buổi họp");

        thoatbtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        thoatbtn.setText("Thoát");
        thoatbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoatbtnAncestorRemoved(evt);
            }
        });

        maBuoiHop.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        maBuoiHop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maBuoiHopActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Mã buổi họp");

        xoabtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        xoabtn.setForeground(new java.awt.Color(255, 0, 102));
        xoabtn.setText("Xóa");
        xoabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoabtnActionPerformed(evt);
            }
        });


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(47, 47, 47)
                                .addComponent(maBuoiHop, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(71, 71, 71)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ChuDe)
                                    .addComponent(ThoiGian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DiaDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(142, 142, 142))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(179, 179, 179))))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(xoabtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(thoatbtn)
                .addGap(51, 51, 51)
                .addComponent(capNhatbtn)
                .addGap(68, 68, 68))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ChuDe, DiaDiem, ThoiGian, maBuoiHop});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maBuoiHop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(ThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(DiaDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thoatbtn)
                    .addComponent(capNhatbtn)
                    .addComponent(xoabtn))
                .addGap(23, 23, 23))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ChuDe, DiaDiem, ThoiGian, maBuoiHop});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChuDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChuDeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChuDeActionPerformed

    private void thoatbtnAncestorRemoved(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thoatbtnAncestorRemoved
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Are you sure to close this?","Confirm",JOptionPane.YES_NO_OPTION) == 0) {
            close();
            parentController.refreshData();
        }
    }//GEN-LAST:event_thoatbtnAncestorRemoved

    private void maBuoiHopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maBuoiHopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maBuoiHopActionPerformed

    private void capNhatbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capNhatbtnActionPerformed
        JOptionPane.showMessageDialog(null, "Cập nhật thành công!!");
        CapNhatBuoiHop();
        close();
        parentController.refreshData();
    }//GEN-LAST:event_capNhatbtnActionPerformed
    private void xoabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capNhatbtnActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn xóa buổi họp này?", "Warning!!", JOptionPane.YES_NO_OPTION) == 0) {
            xoaBuoiHop();
            close();
        }

        parentController.refreshData();
    }
    private void CapNhatBuoiHop() {
        // TODO add your handling code here:
        BuoiHop bh =new BuoiHop(maBuoiHop.getText(),ChuDe.getText(),ThoiGian.getDate(),DiaDiem.getText(),0,"null");
        new BuoiHopService().capNhapBuoiHop(bh);
    }
    private void xoaBuoiHop() {
        // TODO add your handling code here:
        BuoiHop bh =new BuoiHop(maBuoiHop.getText(),ChuDe.getText(),ThoiGian.getDate(),DiaDiem.getText(),0,"null");
        new BuoiHopService().deleteBuoiHop(bh);
    }
    void setBuoiHop(){
        ChuDe.setText(buoiHop.getChuDe());
        maBuoiHop.setText(buoiHop.getMaBuoiHop());
        maBuoiHop.setEnabled(false);
        ThoiGian.setDate(buoiHop.getThoiGian());
        DiaDiem.setText(buoiHop.getDiaDiem());
    }
    void close() {
        this.parentFrame.setEnabled(true);
        dispose();

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CapNhatBuoiHop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CapNhatBuoiHop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CapNhatBuoiHop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CapNhatBuoiHop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CapNhatBuoiHop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ChuDe;
    private javax.swing.JTextField DiaDiem;
    private com.toedter.calendar.JDateChooser ThoiGian;
    private javax.swing.JButton capNhatbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField maBuoiHop;
    private javax.swing.JButton thoatbtn;
    private javax.swing.JButton xoabtn;
    // End of variables declaration//GEN-END:variables
}
