/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.BuoiHopManagerFrame;

import Bean.HoKhauBean;
import controllers.BuoiHopController.DiemDanhBuoiHopController;
import controllers.BuoiHopController.ViewBuoiHopController;
import controllers.HoKhauPanelController;
import controllers.NhanKhauManagerPanelController;
import models.*;
import services.DiemDanhService;
import services.HoKhauService;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.List;

/**
 *
 * @author ADMIN
 */
public class DiemDanhBuoiHop extends javax.swing.JFrame {
    private JFrame parentFrame;
    BuoiHop buoiHop;
    private ViewBuoiHopController parentController;
    private DiemDanhBuoiHopController controller;
    private List<HoKhauBean> listHoKhau;
    DefaultTableModel model;

    /**
     * Creates new form DiemDanhBuoiHop
     */
    public DiemDanhBuoiHop() {
        initComponents();
    }
    public DiemDanhBuoiHop(ViewBuoiHopController parentController, JFrame parentFrame, BuoiHop bh) {
        this.parentController = parentController;
        this.parentFrame = parentFrame;
        this.buoiHop=bh;
        this.parentFrame.setEnabled(false);
        initComponents();
//        controller.DiemDanhBuoiHopController(parentController,parentFrame,bh);
//        model = (DefaultTableModel) jTable1.getModel();
//        getMaHoKhautuCCCD ();
        controller = new DiemDanhBuoiHopController(jtfSearch,jtfSearch2, tableJpn, DiemDanhbt,buoiHop);
        controller.setParentJFrame(parentFrame);

        
//        ShowHoKhau();
        setInfo();


        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                if (JOptionPane.showConfirmDialog(null, "Are you sure to close??", "Warning!!", JOptionPane.YES_NO_OPTION) == 0) {
                    close();
                }
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        maCuocHop = new javax.swing.JTextField();
        tenCuocHop = new javax.swing.JTextField();
        jtfSearch2 = new javax.swing.JTextField();
        DiemDanhbt = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        tableJpn = new javax.swing.JPanel();
        jtfSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jButton2.setText("Điểm danh");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Điểm Danh");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Mã cuộc họp");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Tên cuộc họp ");

        maCuocHop.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tenCuocHop.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jtfSearch2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtfSearch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSearch2ActionPerformed(evt);
            }
        });

        DiemDanhbt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DiemDanhbt.setText("Điểm danh");
        DiemDanhbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    choseHoKhau ();
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                } catch (ClassNotFoundException e) {
                    throw new RuntimeException(e);
                }
                JOptionPane.showMessageDialog(null, "Điểm danh thành công!!");
                close();
                parentController.refreshData();
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setText("Thoát");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close();
                parentController.refreshData();
            }
        });

        javax.swing.GroupLayout tableJpnLayout = new javax.swing.GroupLayout(tableJpn);
        tableJpn.setLayout(tableJpnLayout);
        tableJpnLayout.setHorizontalGroup(
            tableJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 749, Short.MAX_VALUE)
        );
        tableJpnLayout.setVerticalGroup(
            tableJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 334, Short.MAX_VALUE)
        );

        jtfSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSearchActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tìm theo CCCD");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Tìm theo hộ khẩu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(316, 316, 316))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(DiemDanhbt)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tableJpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfSearch2)
                            .addComponent(maCuocHop, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tenCuocHop, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtfSearch, tenCuocHop});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tenCuocHop, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maCuocHop, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfSearch2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel5))
                    .addComponent(jtfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableJpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DiemDanhbt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jtfSearch, tenCuocHop});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfSearch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSearch2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSearch2ActionPerformed

    private void jtfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSearchActionPerformed
    void close() {
        this.parentFrame.setEnabled(true);

        dispose();

    }
    private void setInfo() {
//        ChungMinhThuModel cmt = this.nhanKhauBean.getChungMinhThuModel();
        maCuocHop.setText(this.buoiHop.getMaBuoiHop());
        maCuocHop.setEnabled(false);
        tenCuocHop.setText(this.buoiHop.getChuDe());
        tenCuocHop.setEnabled(false);
    }
    private void ShowHoKhau() {
        // TODO add your handling code here:
        listHoKhau = new HoKhauService().getListHoKhau();
        for (HoKhauBean b :listHoKhau) {
            model.addRow(new Object[]{b.getHoKhauModel().getMaHoKhau(),b.getChuHo().getHoTen(),b.getHoKhauModel().getDiaChi()
            });
        }

    }

//    private void choseHoKhau () {
//        int[] index= jTable1.getSelectedColumns();
//            Object[] row = new Object[3];
//            for (int i=0;i<index.length;i++){
//                row[0]=model.getValueAt(index[i],0);
//                row[1]=model.getValueAt(index[i],1);
//                row[2]=model.getValueAt(index[i],2);
//                System.out.println(row[0]);
//            }
//
//    }
    private void choseHoKhau () throws SQLException, ClassNotFoundException {

    List<DiemDanhModel> listChose =   controller.getDiemDanh();
    for (int i=0;i<listChose.size();i++){
//        System.out.println(listChose.get(i).getMaBuoiHop());
//        System.out.println(listChose.get(i).getSoHoKhau());
//        System.out.println(listChose.get(i).getTrangThai());


        if( listChose.get(i).getTrangThai().equals("true")){
            boolean checkxemchuacothiadd =false;
            List<String> listMaHoKhau= new DiemDanhService().getMaHoKhau(listChose.get(i).getMaBuoiHop());

            for (int j=0;j<listMaHoKhau.size();j++){
                if(listChose.get(i).getSoHoKhau().equals(listMaHoKhau.get(j).toString())){
                    checkxemchuacothiadd=true;
                }else {


                }
            }
            if (checkxemchuacothiadd){

//                System.out.println(listChose.get(i).getSoHoKhau()+"Ho khau co roi nen khong can lam gi ca ");
            }else {
//                System.out.println(listChose.get(i).getSoHoKhau()+"Chua co t nen add vao database");
                new DiemDanhService().addDiemDanh(listChose.get(i).getSoHoKhau(),listChose.get(i).getMaBuoiHop());
            }

        }
        if( listChose.get(i).getTrangThai().equals("false")||listChose.get(i).getTrangThai().equals("null")){
            boolean checkxemdacoroithixoa =false;
            List<String> listMaHoKhau= new DiemDanhService().getMaHoKhau(listChose.get(i).getMaBuoiHop());
            for (int j=0;j<listMaHoKhau.size();j++){
                if(listChose.get(i).getSoHoKhau().equals(listMaHoKhau.get(j).toString())){
                    checkxemdacoroithixoa=true;

                }else {

                }
            }
                if (checkxemdacoroithixoa){
                    new DiemDanhService().deleteDiemDanh(listChose.get(i).getSoHoKhau(),listChose.get(i).getMaBuoiHop());
                }else {
//                    System.out.println(listChose.get(i).getSoHoKhau()+"Ho khau chua co nen khong can lam gi ca ");
                }
        }
    }




}

    private void getMaHoKhautuCCCD (){
            System.out.println(jtfSearch2.getText());
            System.out.println(jtfSearch.getText());

    }


    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DiemDanhBuoiHop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DiemDanhBuoiHop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DiemDanhBuoiHop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DiemDanhBuoiHop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DiemDanhBuoiHop().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DiemDanhbt;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jtfSearch;
    private javax.swing.JTextField jtfSearch2;
    private javax.swing.JTextField maCuocHop;
    private javax.swing.JPanel tableJpn;
    private javax.swing.JTextField tenCuocHop;
    // End of variables declaration//GEN-END:variables
}
